apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: liusb9cxv-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/liusb9cxv-dotnet-basic-gitops